#!/usr/bin/env bash
#Write a Bash script that loops from 1 to 10 and:displays bad luck fr the 4th loop iteration - displays good luck fr the 8th loop iteration -displays Best School fr the other iterations
i=1
while [ $i -le  8 ]
do
echo "Best School"
if [ $i -eq 3 ]
then echo "bad luck"
elif [ $i -eq 6 ]
then echo "good luck"
else "Best School"
fi
((i++))
done
