#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes
HOURS=0
while [ $HOURS -lt 13 ]
do
echo "Hour: $HOURS"
MINUTES=1
while [ $MINUTES -lt 60 ]
do
echo $MINUTES
(( expr )) MINUTES+=1
done
(( expr )) HOURS+=1
done

